# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Canvas'
tagline:          'Poems on time travel, romance and first world problems'
description:      'Poems on time travel, romance and first world problems'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Pratish'
  url:            https://www.facebook.com/pratishgupta91

paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          1.0

github:
  repo:           https://github.com/pratishgupta91/pratishgupta91.github.io

# Gems
gems: [jekyll-paginate, jekyll-gist, pygments.rb]